---
title: "R Notebook"
output:
  html_document:
    df_print: paged
  html_notebook: default
  pdf_document: default
---

```{r setup}
library(tidyverse)
library(xlsx)
library(DT)
library(gt)
library(webshot2)
```

# Import data from study database .xlsx file

```{r, import xlsx file}
fname <- "FNIH prospective study database excluding follow-up exams.xlsx"
```

```{r}
q1 <- xlsx::read.xlsx2(file = fname, 2, startRow = 3, endRow = 169)

q1 <- q1 |> 
  select(MES_Rectum, MES_Descending_Colon, contains("NHI_max")) |> 
  mutate(
    across(contains("NHI_max"), as.integer)
  ) |> 
  mutate(
    across(contains("MES_Rectum"), as.integer) 
  ) |> 
   mutate(
    across(contains("MES_Descending_Colon"), as.integer) 
  ) |>
  drop_na()

datatable(q1)
```

```{r}
df_MES_NHI <- read.xlsx2(fname, sheetName = "MES_vs_NHI")
df_MES_NHI_rd <- df_MES_NHI |> 
  mutate(
    across(3:42, as.integer)
  )

df_MES_NHI_rd$location[df_MES_NHI_rd$location == "rectum"] <- "rectum and descending colon"
```

## Rectum plus DC vs AC

```{r}
df_MES_NHI_rd[1,3] <- sum((q1$MES_Rectum == 0) & (q1$MES_Descending_Colon == 0) & (q1$NHI_max_AC == 0))
df_MES_NHI_rd[1,4] <- sum((q1$MES_Rectum == 0) & (q1$MES_Descending_Colon == 0) & (q1$NHI_max_AC == 1))
df_MES_NHI_rd[1,5] <- sum((q1$MES_Rectum == 0) & (q1$MES_Descending_Colon == 0) & (q1$NHI_max_AC == 2))
df_MES_NHI_rd[1,6] <- sum((q1$MES_Rectum == 0) & (q1$MES_Descending_Colon == 0) & (q1$NHI_max_AC == 3))
df_MES_NHI_rd[1,7] <- sum((q1$MES_Rectum == 0) & (q1$MES_Descending_Colon == 0) & (q1$NHI_max_AC == 4))

df_MES_NHI_rd[2,3] <- sum(((q1$MES_Rectum == 1) & (q1$NHI_max_AC == 0)) | ((q1$MES_Descending_Colon == 1) & (q1$NHI_max_AC == 0)))
df_MES_NHI_rd[2,4] <- sum(((q1$MES_Rectum == 1) & (q1$NHI_max_AC == 1)) | ((q1$MES_Descending_Colon == 1) & (q1$NHI_max_AC == 1)))
df_MES_NHI_rd[2,5] <- sum(((q1$MES_Rectum == 1) & (q1$NHI_max_AC == 2)) | ((q1$MES_Descending_Colon == 1) & (q1$NHI_max_AC == 2)))
df_MES_NHI_rd[2,6] <- sum(((q1$MES_Rectum == 1) & (q1$NHI_max_AC == 3)) | ((q1$MES_Descending_Colon == 1) & (q1$NHI_max_AC == 3)))
df_MES_NHI_rd[2,7] <- sum(((q1$MES_Rectum == 1) & (q1$NHI_max_AC == 4)) | ((q1$MES_Descending_Colon == 1) & (q1$NHI_max_AC == 4)))

df_MES_NHI_rd[3,3] <- sum(((q1$MES_Rectum > 1) & (q1$NHI_max_AC == 0)) | ((q1$MES_Descending_Colon > 1) & (q1$NHI_max_AC == 0)))
df_MES_NHI_rd[3,4] <- sum(((q1$MES_Rectum > 1) & (q1$NHI_max_AC == 1)) | ((q1$MES_Descending_Colon > 1) & (q1$NHI_max_AC == 1)))
df_MES_NHI_rd[3,5] <- sum(((q1$MES_Rectum > 1) & (q1$NHI_max_AC == 2)) | ((q1$MES_Descending_Colon > 1) & (q1$NHI_max_AC == 2)))
df_MES_NHI_rd[3,6] <- sum(((q1$MES_Rectum > 1) & (q1$NHI_max_AC == 3)) | ((q1$MES_Descending_Colon > 1) & (q1$NHI_max_AC == 3)))
df_MES_NHI_rd[3,7] <- sum(((q1$MES_Rectum > 1) & (q1$NHI_max_AC == 4)) | ((q1$MES_Descending_Colon > 1) & (q1$NHI_max_AC == 4)))
```

## Rectum plus DC vs TC

```{r}
df_MES_NHI_rd[1,8] <- sum((q1$MES_Rectum == 0) & (q1$MES_Descending_Colon == 0) & (q1$NHI_max_TC == 0))
df_MES_NHI_rd[1,9] <- sum((q1$MES_Rectum == 0) & (q1$MES_Descending_Colon == 0) & (q1$NHI_max_TC == 1))
df_MES_NHI_rd[1,10] <- sum((q1$MES_Rectum == 0) & (q1$MES_Descending_Colon == 0) & (q1$NHI_max_TC == 2))
df_MES_NHI_rd[1,11] <- sum((q1$MES_Rectum == 0) & (q1$MES_Descending_Colon == 0) & (q1$NHI_max_TC == 3))
df_MES_NHI_rd[1,12] <- sum((q1$MES_Rectum == 0) & (q1$MES_Descending_Colon == 0) & (q1$NHI_max_TC == 4))

df_MES_NHI_rd[2,8] <- sum(((q1$MES_Rectum == 1) & (q1$NHI_max_TC == 0) & (q1$MES_Descending_Colon <= 1)) | ((q1$MES_Descending_Colon == 1) & (q1$NHI_max_TC == 0) & (q1$MES_Rectum <= 1)))
df_MES_NHI_rd[2,9] <- sum(((q1$MES_Rectum == 1) & (q1$NHI_max_TC == 1) & (q1$MES_Descending_Colon <= 1)) | ((q1$MES_Descending_Colon == 1) & (q1$NHI_max_TC == 1) & (q1$MES_Rectum <= 1)))
df_MES_NHI_rd[2,10] <- sum(((q1$MES_Rectum == 1) & (q1$NHI_max_TC == 2) & (q1$MES_Descending_Colon <= 1)) | ((q1$MES_Descending_Colon == 1) & (q1$NHI_max_TC == 2) & (q1$MES_Rectum <= 1)))
df_MES_NHI_rd[2,11] <- sum(((q1$MES_Rectum == 1) & (q1$NHI_max_TC == 3) & (q1$MES_Descending_Colon <= 1)) | ((q1$MES_Descending_Colon == 1) & (q1$NHI_max_TC == 3) & (q1$MES_Rectum <= 1)))
df_MES_NHI_rd[2,12] <- sum(((q1$MES_Rectum == 1) & (q1$NHI_max_TC == 4) & (q1$MES_Descending_Colon <= 1)) | ((q1$MES_Descending_Colon == 1) & (q1$NHI_max_TC == 4) & (q1$MES_Rectum <= 1)))

df_MES_NHI_rd[3,8] <- sum(((q1$MES_Rectum > 1) & (q1$NHI_max_TC == 0)) | ((q1$MES_Descending_Colon > 1) & (q1$NHI_max_TC == 0)))
df_MES_NHI_rd[3,9] <- sum(((q1$MES_Rectum > 1) & (q1$NHI_max_TC == 1)) | ((q1$MES_Descending_Colon > 1) & (q1$NHI_max_TC == 1)))
df_MES_NHI_rd[3,10] <- sum(((q1$MES_Rectum > 1) & (q1$NHI_max_TC == 2)) | ((q1$MES_Descending_Colon > 1) & (q1$NHI_max_TC == 2)))
df_MES_NHI_rd[3,11] <- sum(((q1$MES_Rectum > 1) & (q1$NHI_max_TC == 3)) | ((q1$MES_Descending_Colon > 1) & (q1$NHI_max_TC == 3)))
df_MES_NHI_rd[3,12] <- sum(((q1$MES_Rectum > 1) & (q1$NHI_max_TC == 4)) | ((q1$MES_Descending_Colon > 1) & (q1$NHI_max_TC == 4)))
```

### Calculate percaentages across each row
```{r}
df_MES_NHI_rd <- df_MES_NHI_rd |> 
  rowwise() |> 
  mutate(percent_max_ac_nhi_0 = max_ac_nhi_0 / sum(max_ac_nhi_0, max_ac_nhi_1, max_ac_nhi_2, max_ac_nhi_3, max_ac_nhi_4)) |> 
  mutate(percent_max_ac_nhi_1 = max_ac_nhi_1 / sum(max_ac_nhi_0, max_ac_nhi_1, max_ac_nhi_2, max_ac_nhi_3, max_ac_nhi_4)) |> 
  mutate(percent_max_ac_nhi_2 = max_ac_nhi_2 / sum(max_ac_nhi_0, max_ac_nhi_1, max_ac_nhi_2, max_ac_nhi_3, max_ac_nhi_4)) |> 
  mutate(percent_max_ac_nhi_3 = max_ac_nhi_3 / sum(max_ac_nhi_0, max_ac_nhi_1, max_ac_nhi_2, max_ac_nhi_3, max_ac_nhi_4)) |> 
  mutate(percent_max_ac_nhi_4 = max_ac_nhi_4 / sum(max_ac_nhi_0, max_ac_nhi_1, max_ac_nhi_2, max_ac_nhi_3, max_ac_nhi_4))

df_MES_NHI_rd <- df_MES_NHI_rd |> 
  rowwise() |> 
  mutate(percent_max_tc_nhi_0 = max_tc_nhi_0 / sum(max_tc_nhi_0, max_tc_nhi_1, max_tc_nhi_2, max_tc_nhi_3, max_tc_nhi_4)) |> 
  mutate(percent_max_tc_nhi_1 = max_tc_nhi_1 / sum(max_tc_nhi_0, max_tc_nhi_1, max_tc_nhi_2, max_tc_nhi_3, max_tc_nhi_4)) |> 
  mutate(percent_max_tc_nhi_2 = max_tc_nhi_2 / sum(max_tc_nhi_0, max_tc_nhi_1, max_tc_nhi_2, max_tc_nhi_3, max_tc_nhi_4)) |> 
  mutate(percent_max_tc_nhi_3 = max_tc_nhi_3 / sum(max_tc_nhi_0, max_tc_nhi_1, max_tc_nhi_2, max_tc_nhi_3, max_tc_nhi_4)) |> 
  mutate(percent_max_tc_nhi_4 = max_tc_nhi_4 / sum(max_tc_nhi_0, max_tc_nhi_1, max_tc_nhi_2, max_tc_nhi_3, max_tc_nhi_4))
```

```{r}
df_MES_NHI_rd <- df_MES_NHI_rd |> 
  mutate(max_ac_nhi_0_f = paste0(format(round(percent_max_ac_nhi_0 * 100, 1), nsmall = 1), "%\n(", max_ac_nhi_0, ")")) |> 
  mutate(max_ac_nhi_1_f = paste0(format(round(percent_max_ac_nhi_1 * 100, 1), nsmall = 1), "%\n(", max_ac_nhi_1, ")")) |> 
  mutate(max_ac_nhi_2_f = paste0(format(round(percent_max_ac_nhi_2 * 100, 1), nsmall = 1), "%\n(", max_ac_nhi_2, ")")) |> 
  mutate(max_ac_nhi_3_f = paste0(format(round(percent_max_ac_nhi_3 * 100, 1), nsmall = 1), "%\n(", max_ac_nhi_3, ")")) |> 
  mutate(max_ac_nhi_4_f = paste0(format(round(percent_max_ac_nhi_4 * 100, 1), nsmall = 1), "%\n(", max_ac_nhi_4, ")")) |> 
  mutate(max_tc_nhi_0_f = paste0(format(round(percent_max_tc_nhi_0 * 100, 1), nsmall = 1), "%\n(", max_tc_nhi_0, ")")) |> 
  mutate(max_tc_nhi_1_f = paste0(format(round(percent_max_tc_nhi_1 * 100, 1), nsmall = 1), "%\n(", max_tc_nhi_1, ")")) |> 
  mutate(max_tc_nhi_2_f = paste0(format(round(percent_max_tc_nhi_2 * 100, 1), nsmall = 1), "%\n(", max_tc_nhi_2, ")")) |> 
  mutate(max_tc_nhi_3_f = paste0(format(round(percent_max_tc_nhi_3 * 100, 1), nsmall = 1), "%\n(", max_tc_nhi_3, ")")) |> 
  mutate(max_tc_nhi_4_f = paste0(format(round(percent_max_tc_nhi_4 * 100, 1), nsmall = 1), "%\n(", max_tc_nhi_4, ")")) 
```

## NHI rectum plus DC vs AC

```{r}
MES_NHI_rd_a_per <- df_MES_NHI_rd |> 
  select(location, mes_index, percent_max_ac_nhi_0:percent_max_ac_nhi_4) |> 
  gt() |> 
  fmt_percent(
    decimals = 1
  ) |> 
  tab_header(
    title = md("**Max NHI in Ascending Colon vs MES in Rectum and Descending Colon**")
  ) |> 
  tab_spanner(
    label = "Max NHI in Ascending Colon",
    columns = starts_with("percent")
  ) |> 
  cols_label(
    percent_max_ac_nhi_0 = 0,
    percent_max_ac_nhi_1 = 1,
    percent_max_ac_nhi_2 = 2,
    percent_max_ac_nhi_3 = 3,
    percent_max_ac_nhi_4 = 4,
    mes_index = "MES"
#  ) |> 
#  data_color(
#    columns = 3:7,
#    method = "numeric",
#    palette = c("blue", "red"),
#    domain = c(0,1)
  )

MES_NHI_rd_a <- df_MES_NHI_rd |> 
  select(location, mes_index, max_ac_nhi_0:max_ac_nhi_4) |> 
  gt() |> 
  tab_header(
    title = md("**Max NHI in Ascending Colon vs MES in Rectum and Descending Colon**")
  ) |> 
  tab_spanner(
    label = "Max NHI in Ascending Colon",
    columns = starts_with("max")
  ) |> 
  cols_label(
    max_ac_nhi_0 = 0,
    max_ac_nhi_1 = 1,
    max_ac_nhi_2 = 2,
    max_ac_nhi_3 = 3,
    max_ac_nhi_4 = 4,
    mes_index = "MES"
  )
```

## NHI rectum plus DC vs TC

```{r}
MES_NHI_rd_t_per <- df_MES_NHI_rd |> 
  select(location, mes_index, percent_max_tc_nhi_0:percent_max_tc_nhi_4) |> 
  gt() |> 
  fmt_percent(
    decimals = 1
  ) |> 
  tab_header(
    title = md("**Max NHI in Transvere Colon vs Rectum and Descending Colon**")
  ) |> 
  tab_spanner(
    label = "Max NHI in Transverse Colon",
    columns = starts_with("percent")
  ) |> 
  cols_label(
    percent_max_tc_nhi_0 = 0,
    percent_max_tc_nhi_1 = 1,
    percent_max_tc_nhi_2 = 2,
    percent_max_tc_nhi_3 = 3,
    percent_max_tc_nhi_4 = 4,
    mes_index = "MES"
#  ) |> 
#  data_color(
#    columns = 3:7,
#    method = "numeric",
#    palette = c("blue", "red"),
#    domain = c(0,1)
  )

MES_NHI_rd_t <- df_MES_NHI_rd |> 
  select(location, mes_index, max_tc_nhi_0:max_tc_nhi_4) |> 
  gt() |> 
  tab_header(
    title = md("**Max NHI in Transverse Colon vs MES in Rectum and Descending Colon**")
  ) |> 
  tab_spanner(
    label = "Max NHI in Transverse Colon",
    columns = starts_with("max")
  ) |> 
  cols_label(
    max_tc_nhi_0 = 0,
    max_tc_nhi_1 = 1,
    max_tc_nhi_2 = 2,
    max_tc_nhi_3 = 3,
    max_tc_nhi_4 = 4,
    mes_index = "MES"
  )
```

```{r}
MES_NHI_rd_a
MES_NHI_rd_a_per
MES_NHI_rd_t
MES_NHI_rd_t_per
```
#Separate tables
```{r}
MES_NHI_rd_a_f <- df_MES_NHI_rd |> 
  select(location, mes_index, max_ac_nhi_0_f:max_ac_nhi_4_f, percent_max_ac_nhi_0:percent_max_ac_nhi_4) |> 
  gt() |> 
  tab_header(
    title = md("**Max NHI in Ascending Colon vs MES in Rectum and Descending Colon**")
  ) |> 
  tab_spanner(
    label = "Max NHI in Ascending Colon",
    columns = contains("ac_nhi")
  ) |> 
  cols_label(
    max_ac_nhi_0_f = 0,
    max_ac_nhi_1_f = 1,
    max_ac_nhi_2_f = 2,
    max_ac_nhi_3_f = 3,
    max_ac_nhi_4_f = 4,
    mes_index = "Max MES"
  ) |> 
#  data_color(
#    columns = 13:22,
#    direction = "column",
#    target_columns = 3:12,
#    method = "numeric",
#    palette = c("blue", "red"),
#    domain = c(0,1)
#  ) |> 
  cols_hide(starts_with("percent"))

MES_NHI_rd_a_f 
```

```{r}
MES_NHI_rd_t_f <- df_MES_NHI_rd |> 
  select(location, mes_index, max_tc_nhi_0_f:max_tc_nhi_4_f, percent_max_tc_nhi_0:percent_max_tc_nhi_4) |> 
  gt() |> 
  tab_header(
    title = md("**Max NHI in Transverse Colon vs MES in Rectum and Descending Colon**")
  ) |> 
   tab_spanner(
    label = "Max NHI in Transverse Colon",
    columns = contains("tc_nhi")
  ) |>
  cols_label(
    max_tc_nhi_0_f = 0,
    max_tc_nhi_1_f = 1,
    max_tc_nhi_2_f = 2,
    max_tc_nhi_3_f = 3,
    max_tc_nhi_4_f = 4,
    mes_index = "Max MES"
  ) |> 
#  data_color(
#    columns = 13:22,
#    direction = "column",
#    target_columns = 3:12,
#    method = "numeric",
#    palette = c("blue", "red"),
#    domain = c(0,1)
#  ) |> 
  cols_hide(starts_with("percent"))

MES_NHI_rd_t_f
```


#Combined Table
```{r}
MES_NHI_rd_at_per <- df_MES_NHI_rd |> 
  select(location, mes_index, max_ac_nhi_0_f:max_ac_nhi_4_f, max_tc_nhi_0_f:max_tc_nhi_4_f, percent_max_ac_nhi_0:percent_max_ac_nhi_4, percent_max_tc_nhi_0:percent_max_tc_nhi_4) |> 
  gt() |> 
  tab_header(
    title = md("**Max NHI vs MES in Rectum and Descending Colon**")
  ) |> 
  tab_spanner(
    label = "Max NHI in Ascending Colon",
    columns = contains("ac_nhi")
  ) |> 
   tab_spanner(
    label = "Max NHI in Transverse Colon",
    columns = contains("tc_nhi")
  ) |>
  cols_label(
    max_ac_nhi_0_f = 0,
    max_ac_nhi_1_f = 1,
    max_ac_nhi_2_f = 2,
    max_ac_nhi_3_f = 3,
    max_ac_nhi_4_f = 4,
    max_tc_nhi_0_f = 0,
    max_tc_nhi_1_f = 1,
    max_tc_nhi_2_f = 2,
    max_tc_nhi_3_f = 3,
    max_tc_nhi_4_f = 4,
    mes_index = "Max MES"
  ) |> 
#  data_color(
#    columns = 13:22,
#    direction = "column",
#    target_columns = 3:12,
#    method = "numeric",
#    palette = c("blue", "red"),
#    domain = c(0,1)
#  ) |> 
  cols_hide(starts_with("percent"))
```

```{r}
MES_NHI_rd_at_per
```

```{r, eval=FALSE}
MES_NHI_rd_at_per |> 
  gtsave(filename = "output_tables/mes_rd_nhi_at.png")

MES_NHI_rd_a_f |> 
  gtsave(filename = "output_tables/mes_rd_nhi_a.png")

MES_NHI_rd_t_f |> 
  gtsave(filename = "output_tables/mes_rd_nhi_t.png")
```
```{r, eval=FALSE}
MES_NHI_rd_at_per |> 
  gtsave(filename = "output_tables/mes_rd_nhi_at.docx")

MES_NHI_rd_a_f |> 
  gtsave(filename = "output_tables/mes_rd_nhi_a.docx")

MES_NHI_rd_t_f |> 
  gtsave(filename = "output_tables/mes_rd_nhi_t.docx")
```
